[package]
name = "reth-evm-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Reth
reth-chainspec.workspace = true
reth-ethereum-forks.workspace = true
reth-evm.workspace = true
reth-primitives = { workspace = true, features = ["reth-codec"] }
reth-revm.workspace = true
reth-ethereum-consensus.workspace = true
reth-consensus.workspace = true
<<<<<<< HEAD
reth-tee.workspace = true
reth-tracing.workspace = true
=======
>>>>>>> 5ef21cdfec9801b12dd740acc00970c5c778a2f2

# Ethereum
revm-primitives.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-sol-types.workspace = true
alloy-consensus.workspace = true
<<<<<<< HEAD

# misc
secp256k1.workspace = true
=======
>>>>>>> 5ef21cdfec9801b12dd740acc00970c5c778a2f2

[dev-dependencies]
reth-testing-utils.workspace = true
reth-evm = { workspace = true, features = ["test-utils"] }
reth-revm = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true, features = ["secp256k1"] }
reth-execution-types.workspace = true
<<<<<<< HEAD
=======
secp256k1.workspace = true
>>>>>>> 5ef21cdfec9801b12dd740acc00970c5c778a2f2
serde_json.workspace = true
alloy-genesis.workspace = true

[features]
default = ["std"]
std = [
	"reth-consensus/std",
	"reth-primitives/std",
	"reth-revm/std",
	"alloy-consensus/std",
	"alloy-eips/std",
	"alloy-genesis/std",
	"alloy-primitives/std",
	"revm-primitives/std",
	"secp256k1/std",
	"reth-ethereum-forks/std"
]
