[package]
name ="reth-rpc-seismic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]

reth-chainspec.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
reth-primitives.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-rpc-types.workspace = true
reth-rpc.workspace = true
reth-node-builder.workspace = true
reth-provider.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-network-api.workspace = true
reth-rpc-eth-api.workspace = true
reth-tasks.workspace = true
reth-rpc-types-compat.workspace = true
reth-rpc-eth-types.workspace = true
alloy-dyn-abi.workspace = true
alloy-network.workspace = true
parking_lot = "0.12"
thiserror = "1.0"
jsonrpsee-types = "0.24"
derive_more = "0.99.17"
dyn-clone = "1.0.17"
seismic-transaction.workspace = true
reth-evm-seismic.workspace = true
reth-helpers-seismic.workspace = true

# clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
tokio.workspace = true
jsonrpsee = { workspace = true, features = ["server", "macros", "client"] }
secp256k1 = { version = "0.29", default-features = false, features = [
    "global-context",
    "recovery",
] }
tracing.workspace = true
async-trait.workspace = true

serde_json.workspace = true
[lints]
workspace = true
