ethereum_package:
  participants:
    - el_type: reth
      el_extra_params:
        - "--rpc.eth-proof-window=100"
      cl_type: teku
optimism_package:
  chains:
    - participants:
        - el_type: op-reth
          el_image: op-reth
          cl_type: op-node
