[metadata]
version = "0.1.0"
description = "Seismic testnet genesis contracts"

# Optional: defaults to main branch if not specified
base_url = "https://raw.githubusercontent.com/SeismicSystems/seismic-contracts/main"

[contracts.MultisigUpgradeOperator]
artifact = "artifacts/MultisigUpgradeOperator.json"
address = "0x2001"

[contracts.UpgradeOperator]
artifact = "artifacts/UpgradeOperator.json"
address = "0x2002"

[contracts.ShieldedDelegationAccount]
artifact = "artifacts/ShieldedDelegationAccount.json"
address = "0x2003"
