//! Seismic-Reth chain specs.

#![doc(
    html_logo_url = "https://raw.githubusercontent.com/paradigmxyz/reth/main/assets/reth-docs.png",
    html_favicon_url = "https://avatars0.githubusercontent.com/u/97369466?s=256",
    issue_tracker_base_url = "https://github.com/SeismicSystems/seismic-reth/issues/"
)]
#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
#![cfg_attr(not(feature = "std"), no_std)]

use std::sync::Arc;

use alloy_chains::Chain;
use alloy_genesis::Genesis;
use alloy_primitives::{b256, B256, U256};
use reth_chainspec::{make_genesis_header, ChainSpec};
use reth_primitives_traits::{sync::LazyLock, SealedHeader};
use reth_seismic_forks::{
    SEISMIC_DEV_HARDFORKS, SEISMIC_MAINNET_HARDFORKS, SEISMIC_TESTNET_HARDFORKS,
};

mod spec;
pub use spec::SeismicChainSpec;

/// Normalizes a parsed genesis so all Seismic specs derive their config from one place:
/// enables DAO-fork support.
const fn normalize_genesis(mut genesis: Genesis) -> Genesis {
    genesis.config.dao_fork_support = true;
    genesis
}

/// Genesis hash for the Seismic mainnet
/// Calculated by rlp encoding the genesis header and hashing it.
///
/// Must be updated whenever `res/genesis/mainnet.json` changes, or when
/// [`SEISMIC_MAINNET_HARDFORKS`] changes which forks are active at genesis
/// (active forks add fields to the header). The `genesis_header_hash` test
/// recomputes it and fails on drift.
///
/// Reproduce the correct value with
/// `seismic-reth genesis-hash --chain crates/seismic/chainspec/res/genesis/mainnet.json`
/// — the file path matters: `--chain mainnet` echoes this pinned constant back.
pub const SEISMIC_MAINNET_GENESIS_HASH: B256 =
    b256!("0xade98a3ac8ed86de0ac2215b679c8d0c5fde21c528d184eed86bfefd961f6992");

/// Genesis hash for the Seismic public testnet.
///
/// This hash and its `res/genesis/testnet.json` file describe a running
/// network: both are immutable snapshots of what it launched with, never
/// regenerated by the genesis builder. Shipping the file here lets a node
/// join with `--chain testnet` on a genesis from the client it audited rather
/// than one handed over by whoever runs the deploy tooling.
///
/// Reproduce the value with
/// `seismic-reth genesis-hash --chain crates/seismic/chainspec/res/genesis/testnet.json`.
/// The `genesis_header_hash` test recomputes the hash and fails on drift.
pub const SEISMIC_TESTNET_GENESIS_HASH: B256 =
    b256!("0x6a84b179cf4f4b4d81d05b7078661d696eeb8d22baea30911dfba2f7165ae5b4");

/// Genesis hash for the Seismic devnet
/// Calculated by rlp encoding the genesis header and hashing it.
///
/// Must be updated whenever `res/genesis/dev.json` changes, or when
/// [`SEISMIC_DEV_HARDFORKS`] changes which forks are active at genesis
/// (active forks add fields to the header).
///
/// Scope: this covers the built-in `--chain dev` template only. Every other
/// `--chain` value is parsed as a genesis file whose hash is computed from its
/// own content, so a per-network genesis carrying injected registry storage is
/// a different chain and needs no constant here.
///
/// Reproduce the correct value with
/// `seismic-reth genesis-hash --chain crates/seismic/chainspec/res/genesis/dev.json`
/// The `genesis_header_hash` test recomputes it and fails on drift.
pub const SEISMIC_DEV_GENESIS_HASH: B256 =
    b256!("0x2302293c3db44f79362faa1f267e512799c2a7e9fd8d23d61d3180edc4b8c736");

/// Seismic devnet specification
///
/// # Panics
/// Panics if the embedded `dev.json` genesis file cannot be deserialized.
/// Indicates a build error, not a runtime issue.
#[allow(clippy::expect_used)] // Documented panic - genesis deserialization is required
pub static SEISMIC_DEV: LazyLock<Arc<SeismicChainSpec>> = LazyLock::new(|| {
    let genesis: Genesis = serde_json::from_str(include_str!("../res/genesis/dev.json"))
        .expect("FATAL: Can't deserialize Dev genesis json");
    let genesis = normalize_genesis(genesis);

    let hardforks = SEISMIC_DEV_HARDFORKS.clone();
    let inner = ChainSpec {
        chain: Chain::from_id(5124),
        genesis_header: SealedHeader::seal_slow(make_genesis_header(&genesis, &hardforks)),
        genesis,
        paris_block_and_final_difficulty: Some((0, U256::from(0))),
        hardforks,
        ..Default::default()
    };
    SeismicChainSpec::with_genesis_hash(inner, SEISMIC_DEV_GENESIS_HASH).into()
});

/// Seismic public testnet specification.
///
/// # Panics
/// Panics if the embedded `testnet.json` genesis file cannot be deserialized.
/// Indicates a build error, not a runtime issue.
#[allow(clippy::expect_used)] // Documented panic - genesis deserialization is required
pub static SEISMIC_TESTNET: LazyLock<Arc<SeismicChainSpec>> = LazyLock::new(|| {
    let genesis: Genesis = serde_json::from_str(include_str!("../res/genesis/testnet.json"))
        .expect("FATAL: Can't deserialize Testnet genesis json");
    let genesis = normalize_genesis(genesis);

    let hardforks = SEISMIC_TESTNET_HARDFORKS.clone();
    let inner = ChainSpec {
        chain: Chain::from_id(5124),
        genesis_header: SealedHeader::seal_slow(make_genesis_header(&genesis, &hardforks)),
        genesis,
        paris_block_and_final_difficulty: Some((0, U256::from(0))),
        hardforks,
        ..Default::default()
    };
    SeismicChainSpec::with_genesis_hash(inner, SEISMIC_TESTNET_GENESIS_HASH).into()
});

/// Seismic Mainnet
///
/// # Panics
/// Panics if the embedded `mainnet.json` genesis file cannot be deserialized.
/// Indicates a build issue, not a runtime issue.
#[allow(clippy::expect_used)] // Documented panic - genesis deserialization is required
pub static SEISMIC_MAINNET: LazyLock<Arc<SeismicChainSpec>> = LazyLock::new(|| {
    let genesis: Genesis = serde_json::from_str(include_str!("../res/genesis/mainnet.json"))
        .expect("FATAL: Can't deserialize Mainnet genesis json");
    let genesis = normalize_genesis(genesis);

    let hardforks = SEISMIC_MAINNET_HARDFORKS.clone();
    let inner = ChainSpec {
        chain: Chain::from_id(5123),
        genesis_header: SealedHeader::seal_slow(make_genesis_header(&genesis, &hardforks)),
        genesis,
        paris_block_and_final_difficulty: Some((0, U256::from(0))),
        hardforks,
        ..Default::default()
    };
    SeismicChainSpec::with_genesis_hash(inner, SEISMIC_MAINNET_GENESIS_HASH).into()
});

#[cfg(test)]
#[allow(clippy::expect_used)] // Test code - expect on failure is acceptable
#[allow(clippy::unwrap_used)] // Test code - unwrap on failure is acceptable
#[allow(clippy::panic)] // Test code - panic on failure is acceptable
mod tests {
    use crate::*;
    use alloy_consensus::{constants::MAINNET_GENESIS_HASH, BlockHeader, Sealable};
    use alloy_primitives::address;
    use reth_chainspec::MAINNET;
    use reth_ethereum_forks::EthereumHardfork;
    use reth_seismic_forks::SeismicHardfork;
    use reth_seismic_primitives::SeismicHeader;

    #[test]
    fn seismic_mainnet_genesis() {
        let genesis = SEISMIC_MAINNET.genesis_header();
        let eth_genesis = MAINNET.genesis_header();
        assert_ne!(
            genesis.hash_slow(),
            eth_genesis.hash_slow(),
            "Seismic spec should not match eth genesis"
        );
        assert_eq!(
            genesis.hash_slow(),
            SEISMIC_MAINNET_GENESIS_HASH,
            "Seismic spec has correct genesis hash"
        );
    }

    // Test that the latest fork id is the latest seismic fork (mercury)
    #[test]
    fn latest_seismic_mainnet_fork_id_with_builder() {
        let seismic_mainnet = &SEISMIC_MAINNET;
        assert_eq!(
            seismic_mainnet.hardfork_fork_id(SeismicHardfork::Mercury).unwrap(),
            seismic_mainnet.latest_fork_id()
        )
    }

    // Check display contains all eth mainnet hardforks and the seismic mercury fork
    #[test]
    fn display_hardforks() {
        let content = SEISMIC_MAINNET.display_hardforks().to_string();
        let eth_mainnet = EthereumHardfork::mainnet();
        for (eth_hf, _) in eth_mainnet {
            assert!(content.contains(eth_hf.name()), "missing hardfork {eth_hf}");
        }
        assert!(content.contains("Mercury"));
    }

    /// The dev genesis is regenerated from `res/genesis/manifest.toml`, so it is
    /// stored in the genesis builder's canonical form: a rebuild that changes no
    /// contract is then an empty diff, and a contract bump is all a reviewer has
    /// to read.
    #[test]
    fn dev_genesis_is_canonical() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("res/genesis/dev.json");
        let genesis = reth_seismic_genesis_builder::load_genesis(&path).expect("dev.json parses");

        assert_eq!(
            std::fs::read_to_string(&path).expect("dev.json is readable"),
            reth_seismic_genesis_builder::canonical_json(&genesis).expect("dev.json reserializes"),
            "dev.json is not in canonical form; regenerate it with the genesis-builder binary"
        );
    }

    #[test]
    fn templates_ship_no_storage_at_registry_address() {
        let registry = address!("0x1000000000000000000000000000000000000001");

        for (network, spec) in
            [("dev", &SEISMIC_DEV), ("testnet", &SEISMIC_TESTNET), ("mainnet", &SEISMIC_MAINNET)]
        {
            let account = spec.genesis.alloc.get(&registry).expect("registry address is allocated");

            assert!(
                account.storage.as_ref().is_none_or(|storage| storage.is_empty()),
                "{network} genesis ships storage at the registry address: accepted admission IDs \
                 are network-specific and injected into deploy-owned genesis files, so committed \
                 templates carry no policy and an empty registry fails closed"
            );
        }
    }

    #[test]
    fn dev_removes_the_legacy_token_seed_but_retains_the_proxy() {
        let legacy_token = address!("790701048922e265105fd6a4467a2901c2201c43");
        assert!(
            !SEISMIC_DEV.genesis.alloc.contains_key(&legacy_token),
            "dev must not preseed a nonzero public balance at the obsolete token address"
        );
        let holder = address!("976ea74026e726554db657fa54763abd0c3a0aa9");
        assert!(
            SEISMIC_DEV.genesis.alloc.get(&holder).unwrap().balance.is_zero(),
            "the token-only holder must be funded with tokens through execution"
        );
        for address in [
            address!("57ab1ed011a20000000000000000000000000000"),
            address!("c4120d2e54b07854ab8b96512fd8eedf3fc415d3"),
        ] {
            assert!(
                SEISMIC_DEV
                    .genesis
                    .alloc
                    .get(&address)
                    .unwrap()
                    .code
                    .as_ref()
                    .is_some_and(|code| !code.is_empty()),
                "proxy and ProxyAdmin must remain allocated"
            );
        }
    }

    #[test]
    fn deprecated_aes_lib_is_testnet_only() {
        let aes_lib = address!("1000000000000000000000000000000000000003");
        assert!(
            !SEISMIC_DEV.genesis.alloc.contains_key(&aes_lib),
            "dev genesis must not include the deprecated AesLib"
        );
        assert!(
            SEISMIC_TESTNET.genesis.alloc.contains_key(&aes_lib),
            "running testnet genesis must remain immutable"
        );
    }

    #[test]
    fn genesis_header_hash() {
        // Confirm how eth mainnet genesis header hash is calculated
        let expected = MAINNET_GENESIS_HASH;
        let genesis =
            serde_json::from_str(include_str!("../../../chainspec/res/genesis/mainnet.json"))
                .expect("Can't deserialize Mainnet genesis json");
        let hardforks = EthereumHardfork::mainnet().into();
        let genesis_header = make_genesis_header(&genesis, &hardforks);
        let actual_hash = genesis_header.hash_slow();
        assert_eq!(actual_hash, expected);

        // Seismic genesis hashes are the hashes of the *Seismic* header (zero sub-second
        // component wrapped around the stock genesis header), not of the stock header.
        for (name, json, hardforks, expected) in [
            (
                "mainnet",
                include_str!("../res/genesis/mainnet.json"),
                SEISMIC_MAINNET_HARDFORKS.clone(),
                SEISMIC_MAINNET_GENESIS_HASH,
            ),
            (
                "testnet",
                include_str!("../res/genesis/testnet.json"),
                SEISMIC_TESTNET_HARDFORKS.clone(),
                SEISMIC_TESTNET_GENESIS_HASH,
            ),
            (
                "dev",
                include_str!("../res/genesis/dev.json"),
                SEISMIC_DEV_HARDFORKS.clone(),
                SEISMIC_DEV_GENESIS_HASH,
            ),
        ] {
            let genesis: Genesis =
                serde_json::from_str(json).expect("Can't deserialize Seismic genesis json");
            let genesis = normalize_genesis(genesis);
            let stock_header = make_genesis_header(&genesis, &hardforks);
            let seismic_header = SeismicHeader::from(stock_header.clone());
            assert_eq!(seismic_header.timestamp_millis_part, 0);
            assert_ne!(seismic_header.hash_slow(), stock_header.hash_slow(), "{name}");
            assert_eq!(
                seismic_header.hash_slow(),
                expected,
                "{name} genesis hash drifted; new hash: {:#x}",
                seismic_header.hash_slow()
            );
        }
    }

    #[test]
    fn specs_expose_the_seismic_genesis_hash_consistently() {
        for (spec, expected) in [
            (&*SEISMIC_DEV, SEISMIC_DEV_GENESIS_HASH),
            (&*SEISMIC_TESTNET, SEISMIC_TESTNET_GENESIS_HASH),
            (&*SEISMIC_MAINNET, SEISMIC_MAINNET_GENESIS_HASH),
        ] {
            assert_eq!(spec.genesis_hash(), expected);
            assert_eq!(spec.sealed_genesis_header().hash(), expected);
            // The inner stock spec is re-sealed with the Seismic hash so fork ids match.
            assert_eq!(spec.inner().genesis_hash(), expected);
            assert_eq!(spec.genesis_header().timestamp(), spec.genesis().timestamp);
        }
    }
}
