name: Seismic CI

on:
  push:
    branches: [seismic]
  pull_request:
    branches: [seismic]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  build:
    runs-on: large-github-runner
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
      - name: cargo check (workspace)
        run: cargo check --workspace

  warnings:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "warnings-cache"
      - name: cargo check warnings
        run: RUSTFLAGS="-D warnings" cargo check

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "clippy-cache"
      - name: Clippy (seismic crates)
        run: |
          cargo clippy \
            -p reth-seismic-primitives \
            -p reth-seismic-chainspec \
            -p reth-seismic-evm \
            -p reth-seismic-payload-builder \
            -p reth-seismic-node \
            -p reth-seismic-rpc \
            -p reth-seismic-cli \
            -p reth-seismic-txpool \
            -p reth-seismic-forks \
            -p seismic-reth \
            --lib --tests --no-deps \
            -- -D warnings \
            -W clippy::unwrap_used \
            -W clippy::expect_used \
            -W clippy::indexing_slicing \
            -W clippy::panic \
            -W clippy::unreachable \
            -W clippy::todo

  unit-test:
    runs-on: large-github-runner
    timeout-minutes: 30
    env:
      SEISMIC_CI: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "integration-test-cache"
      - name: seismic-node test
        # see profile.default in .config/nextest.toml for filtered tests
        run: cargo nextest run --workspace -E '!kind(test)' --no-fail-fast

  integration-test:
    runs-on: large-github-runner
    timeout-minutes: 30
    env:
      SEISMIC_CI: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "integration-test-cache"
      - name: seismic-node test
        # see profile.default in .config/nextest.toml for filtered tests
        run: cargo nextest run --workspace -E 'kind(test)' --no-fail-fast
